### ISSUE TITLE
Add/Edit a Book - SRSC_2.1.2 & SRSC_2.1.3

### ISSUE THREAD

**Issue by Tabassum-momin** [aakvatech/LibMS#10]
- [x] #24
- [x] 2. Possible to connect the information of 'Book Category' and 'Book Type' fields?
- [x] 3. On selection of 'Donated Book' as 'yes', rearrange the donation related fields as a section, for easy navigation.
- [x] 4. 'Book Code' / 'Book Tag' - Which field would be used as unique Book access number and DDC respectively?
- [x] 5. Auto-populate 'Subject' on entering DDC code. Make 'Subject' field read-only.
- [x] 6. When eBook entry is being created, the 'no. of copies' field shouldn't be accessible.
- [x] 7. No. of Copies in 'Donation' section must be <= No. of copies in 'Book Details' section.

**Comment by Tabassum-momin** [comment]
- [x] 8. ISBN is marked mandatory. On receiving error from ISBN API, 'save' button don't work.
- [x] 9. Digital Book related fields shall be displayed only after 'Is Digital Book' is marked YES.
- [x] 10. Book Title fields shall be available for 5 languages (English, Gujarati, Arabic, Urdu, Farsi)

**Comment by ramjanalilal** [comment]
Point 8:

<img width="1295" alt="Screenshot 2024-06-13 at 5 35 07 PM" src="https://github.com/aakvatech/LibMS/assets/30793962/c414c942-81f6-422e-9060-c53d9f549841">

Point 9: 

<img width="1287" alt="Screenshot 2024-06-13 at 5 38 56 PM" src="https://github.com/aakvatech/LibMS/assets/30793962/0e8dc735-7889-47df-a66b-4fe47c273a59">


Point 10:

At time when we deploy the production create custom field.

**Comment by liyakatalilal** [comment]
> * 10. Book Title fields shall be available for 5 languages (English, Gujarati, Arabic, Urdu, Farsi)

SRSE_2.4.1 in excel tracker.
To be added during production deployment. Total 5 languages: English, Gujarati, Urdu, Arabic, Farsi

**Comment by Tabassum-momin** [comment]
All changes verified and closed. Point #10 to be taken care during UAT and prod. Hence closing this issue.

**Comment by Tabassum-momin** [comment]
Need to manually fill 'naming series'. While saving doc, it says 'Asset Category is mandatory for fixed Asset item'
![image](https://github.com/user-attachments/assets/ea11495b-0fac-4365-a07c-794824f8c9f7)

**Comment by ramjanalilal** [comment]
![Screenshot 2024-08-12 at 6 23 39 PM](https://github.com/user-attachments/assets/88c592b3-aec1-4f95-be11-fcd9cc44deca)
in a Library setting the field is required

**Comment by Tabassum-momin** [comment]
Added this point in production readiness task
