### ISSUE TITLE
Too many informative messages pop-up while attaching a file and saving the doc.

### ISSUE THREAD

**Issue by ramjanalilal** [aakvatech/LibMS#24]
All these notifications are kept to ensure testing. These will be removed in UAT and production

**Comment by ramjanalilal** [comment]
for right now validation when we setup production all message will remove

**Comment by Tabassum-momin** [comment]
Points to take care while refactoring informative and warning messages:

- [ ] Remove unwanted messages, warnings and errors
- [ ] To ease user, rephrase the messages and errors

**Comment by Tabassum-momin** [comment]
All production tasks are listed here aakvatech/lib_issue#6 . Hence closing this task
