### ISSUE TITLE
Sub-Library Circulation SRSC_4.2.1

### ISSUE THREAD

**Issue by ramjanalilal** [aakvatech/LibMS#27]
- [ ] The user should be able to issue a book for a given member ID. 
- [ ] Perform member verification if the book is issued on behalf of others.
- [x] Allow a maximum of 4 books issued under a single member ID.
- [ ] Book issue duration can be 1- or 30 days based on membership type.
- [ ] Auto Trigger asset workflow status based on the transaction.
- [ ] In the Book Transaction Panelty Section, calculate the remaining days based on the Return Date and create a summary.

**Comment by Tabassum-momin** [comment]
Duplicate. Requirements taken care under Issue and Return SRSC_2.2.2 and SRSC_2.2.3
