### ISSUE TITLE
Enable Data Import for custom DocTypes

### ISSUE THREAD

**Issue by Tabassum-momin** [aakvatech/LibMS#36]
Make settings to Allow Data Import for below mentioned DocTypes:
1. Author
2. Translator
3. Editor
4. Language
5. Book
6. ...

**Comment by ramjanalilal** [comment]
<img width="1506" alt="Screenshot 2024-07-29 at 10 14 17 AM" src="https://github.com/user-attachments/assets/88a94257-2704-4656-85f4-3425e5e41b13">

allowed to data import all doctype

**Comment by Tabassum-momin** [comment]
Reopening this issue, as changes aren't available on dev yet.

**Comment by Tabassum-momin** [comment]
@ramjanalilal , The list of doctypes mentioned above are not exhaustive. Can you please allow Import for all custom doctypes in LMS?

EDIT:
Need Data Import for below docTypes too:
1. DDC
2. Book Category
3. Asset

**Comment by ramjanalilal** [comment]
https://github.com/aakvatech/LibMS/pull/58#issue-2460944871

PR Raise also asset have already in standard
