### ISSUE TITLE
Scan barcode during Book Transaction

### ISSUE THREAD

**Issue by Tabassum-momin** [aakvatech/LibMS#46]
- [x] 1. Integrate scanner with on 'Book Transaction' page
- [x] 2. When loading book access number from scanner finishes, populate the Transaction detail's table based on 'Transaction Type' and 'Member' fields. (Detailed requirement mentioned at Issue aakvatech/lib_issue#5 and aakvatech/lib_issue#2 )

**Comment by eliusmgani** [comment]
@Tabassum-momin which bug did you find in scan barcode functionality..????

**Comment by Tabassum-momin** [comment]
On change of Transaction date, the due date field isn't populating

**Comment by Tabassum-momin** [comment]
> On change of Transaction date, the due date field isn't populating

This is working fine. Validated with transaction : MLJS-Return-0001

**Comment by Tabassum-momin** [comment]
All requirements under this feature are working fine. Hence closing this issue
