### ISSUE TITLE
Barcode Generator for Asset: Library Book - SRSC_2.1.10

### ISSUE THREAD

**Issue by Tabassum-momin** [aakvatech/LibMS#57]
Print Label - Generate labels for given access number/s (max. 24 at once). Print label/QR codes by allowing user to either 
1. Select a book and its corresponding access numbers OR
2. Manually enter list of Asset access numbers.

**Comment by Tabassum-momin** [comment]
Issues identified:
1. Currently, the QR scanner detects the Generator code and not the book access number.
2. Item field shall populate only books items. No need to have Library Service items in dropdown.
3. Rename Print format 'wewe' with suitable name
4. Details required in each label are : Author_sect, DDC_code, language, access_no and qr_code  (refer sample below)
<img width="563" alt="image" src="https://github.com/user-attachments/assets/15569677-e73f-4636-9508-92a05f0445be">

**Comment by ramjanalilal** [comment]
<img width="1440" alt="Screenshot 2024-08-30 at 9 37 35 AM" src="https://github.com/user-attachments/assets/988d7aa2-0b78-4db7-8b54-c8d9cba8a06a">
<img width="1263" alt="Screenshot 2024-08-30 at 9 20 01 AM" src="https://github.com/user-attachments/assets/21458457-9129-4d8a-ac79-569791e16815">

**Comment by tabassum-momin-mljs** [comment]
The list filters based on 'isFixed Asset'. Is this required? List all books that belong to Normal Book category.
